spring:
  application:
    name: sse-chat-api

server:
  port: 8080

app:
  model:
    base-url: http://localhost:8000/v1
    endpoint: /chat/completions
    name: local-llama
    api-key: ""
    temperature: 0.2
    use-guided-json: false
    lora-name: ""