spring:
  application:
    name: sse-chat-api

server:
  port: 8080

app:
  model:
    base-url: http://localhost:8000/v1
    endpoint: /completions
    name: local-llama
    api-key: ""
    temperature: 0.2
    max-tokens: 64
    use-guided-json: false
    lora-name: ""
  sse:
    heartbeat-seconds: 20
  embedding:
    onnx:
      model-dir: "/Users/shs0920/IdeaProjects/sse-chat-api/models/all-MiniLM-L6-v2"
      tokenizer-json: "/Users/shs0920/IdeaProjects/sse-chat-api/models/all-MiniLM-L6-v2/tokenizer.json"
      max-length: 256
  opensearch:
    base-url: https://localhost:9200
    index: rag_docs
    username: admin
    password: Ab9!qJ7^Lm4?
  dynamo:
    endpoint: http://localhost:8001
    region: ap-northeast-2   # 로컬에선 의미 없음. 아무 리전이나 OK.
    table: rag_raw_docs
  reranker:
    onnx:
      model: models/ms-marco-MiniLM-L-6-v2
      max-length: 256
aws:
  region: ap-northeast-2

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG